version: '3.8'

services:
  web:
    build: .
    container_name: finanzas_pro_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./FinanzasPro.db:/app/FinanzasPro.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
